[phases.setup]
nixPkgs = ["nodejs_20", "python311", "chromium"]

[phases.install]
cmds = [
  "npm install",
  "python -m pip install --upgrade pip",
  "pip install playwright",
  "playwright install chromium --with-deps"
]

[start]
cmd = "node server.js"
